### ISSUE TITLE
Option to share network needn't be documented

### ISSUE THREAD

**Issue by nathanweeks** [nerc-project/nerc-docs#17]
Perhaps this option needn't be mentioned in the user docs if only administrators can see it? (Just a suggestion; if this doc is for admins too, please disregard!)

https://github.com/nerc-project/nerc-docs/blob/a12837ede939d623964dc0a5fef069d3168c1d79/docs/openstack/setting-up-a-network/set-up-a-private-network.md#L21-L22

**Comment by Milstein** [comment]
These lines are now removed as per your suggestion and not applicable for the general user. @nathanweeks
