### ISSUE TITLE
Adding pricing for new Flavors based on `gpu-su-a100sxm`

### ISSUE THREAD

**Issue by Milstein** [nerc-project/nerc-docs#175]
We will be adding 2 new flavors based on Lenovo A100 GPU nodes. Pricing is confirmed.

- [x] Need spec for the new hardware for nerc-docs.
- [x] Need to add these to our main Invoicing Requirement doc for our internal users and also nerc-docs for general users.
- [x] update [calculator](https://docs.google.com/spreadsheets/d/187bQgz3eB3W9OL7x9rrgaJ2pi7u85xMJvUJbnKzzBQM/edit#gid=0)
- [x] Update [Invoice Requirements](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1)

**Comment by joachimweyl** [comment]
Calculator updated. Happy to help review updates made to documents.
