### ISSUE TITLE
Update the public facing pricing documents and caulators to include H100's at $6.04 per GPU

### ISSUE THREAD

**Issue by msdisme** [nerc-project/nerc-docs#220]
We are making an RFP available through Hariri for researchers to get NERC credits. To make the RFP public we need to include the H100 pricing. 

We should be clear in the docs that the H100s will be available early next year. 

Please only display costs for h100s on Openshift Containers—moving them back and forth is not worth the effort. 

@joachimweyl - what details do you need to help figure out standard SUs for 1 GPU?

Not sure this list is exhaustive, but I found references here:

https://nerc-project.github.io/nerc-docs/get-started/cost-billing/how-pricing-works/

and 

https://nerc-project.github.io/nerc-docs/get-started/cost-billing/nerc-pricing-calculator/

Let us explicitly ignore any h100 OpenStack flavors.

**Comment by joachimweyl** [comment]
@msdisme we need to know how many GPUs per system and how much RAM/CPU per system.

**Comment by joachimweyl** [comment]
@Milstein this means:
1 H100 SU = 1 GPU, 64 vCPU, 384 GB RAM

**Comment by msdisme** [comment]
Hi - we are starting to get applications for the Hariri Grants.   How quickly may we get the pages and calculator changes live so Nancy may redirect them.

**Comment by joachimweyl** [comment]
@Milstein let me know how I can help update the documents
[how-pricing-works](https://nerc-project.github.io/nerc-docs/get-started/cost-billing/how-pricing-works/)
and
[nerc-pricing-calculator](https://nerc-project.github.io/nerc-docs/get-started/cost-billing/nerc-pricing-calculator/)

I have updated the [Calculator](https://docs.google.com/spreadsheets/d/187bQgz3eB3W9OL7x9rrgaJ2pi7u85xMJvUJbnKzzBQM/edit?usp=sharing)
